name: student_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  api_client: 
    path: ../api_client
  build_runner: ^2.4.15
  equatable: ^2.0.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
