name: api_client
description: A client to communicate with somnio_starter_example backend
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  http: ^1.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  logger: ^2.0.2+1
  token_provider:
    path: ../token_provider

dev_dependencies:
  build_runner: ^2.4.14
  mocktail: ^1.0.4
  test: ^1.25.14
  very_good_analysis: ^7.0.0
