version = 0.1
[dev.deploy.parameters]
stack_name = "AdaProject"
resolve_s3 = true
s3_prefix = "AdaProject"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
image_repositories = []

[default.deploy.parameters]
stack_name = "AdaProject"
resolve_s3 = true
s3_prefix = "AdaProject"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
disable_rollback = false
