name: auth_client
description: An authentication client implementation
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  rxdart: ^0.28.0
  token_provider:
    path: ../token_provider

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.14
  very_good_analysis: ^7.0.0
