name: planner_repository
description: A repository to handle the career planner data.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies: 
  api_client: 
    path: ../api_client
  build_runner: ^2.4.15
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  logger: ^2.0.2+1


dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
